import os
import discord
import asyncio
from zoneinfo import ZoneInfo
from dotenv import load_dotenv
from discord.ext import tasks,commands
from datetime import datetime, timedelta, time

# TODO sometimes discord shits the bed with 503s, need to handle those errors
# TODO gspread or similiar to automatically added data to google sheet
# TODO log bot output in a log file.
# TODO log attendance in a log file.

# TNTBOT INFO
# - TOKEN is generated by discord for the bot, must be kept secret.
# - IDs are for my own discord server and channels for testing.
# - A guild is a discord server.
# - @commands.guild_only() means Don't allow this command in DMs, because the DM space has no ctx.

DEBUG = True

TZ = ZoneInfo("America/New_York")

# BOT CONFIG
load_dotenv()
TOKEN       = os.getenv('TOKEN')
GUILD_ID    = int(os.getenv('GUILD_ID'))

ALLOWED_USERS = list(map(int, os.getenv('ALLOWED_USERS').split(',')))

class AttendanceCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.jobs = {}

class TNTBot(commands.Bot):
    def __init__(self):
        guild = None
        intents = discord.Intents.default()
        intents.members = True           # Required to see member lists
        intents.voice_states = True      # Required to see who is in voice channels
        intents.message_content = True   # Required to read command messages
        intents.messages = True          # Required to send messages
        intents.guilds = True            # Required to access guild/channel info
        super().__init__(command_prefix="!", intents=intents)

    async def setup_hook(self):
        print("AttendanceCog loaded.")
        await self.add_cog(AttendanceCog(bot))

    async def on_ready(self):
        print(f"Logged in as {self.user}")
        print("Registered commands:")
        for command in self.commands:
            print(f"- {command.name}")
        self.guild = self.get_guild(GUILD_ID)
        if self.guild is None:
            print(f"Could not find guild with ID {GUILD_ID}. "
                  "ERROR: Make sure the bot has been invited to that server.")
            return

    async def on_message(self, message):
        if (message.author.id in ALLOWED_USERS):
            print(f"{message.content}")
            await self.process_commands(message)

    async def on_command_error(self, ctx, error):
        if isinstance(error, commands.CommandNotFound):
            await ctx.send(f"Unknown command. Use `{ctx.prefix}help` to see available commands.")
            return
        elif isinstance(error, commands.MissingRequiredArgument):
            await ctx.send(f"Error: Missing Required Arugment(s)")
            return
        raise error

class HelpCommand(commands.MinimalHelpCommand):
    async def send_pages(self):
        destination = self.get_destination()
        for page in self.paginator.pages:
            emby = discord.Embed(description=page)
            await destination.send(embed=emby)

bot = TNTBot()
bot.help_command = HelpCommand()
bot.run(TOKEN)
