import os
import re
import discord
import asyncio
from typing import Optional
from dataclasses import dataclass, field
from collections import defaultdict
from zoneinfo import ZoneInfo
from dotenv import load_dotenv
from discord.ext import tasks,commands
from datetime import datetime, timedelta, time
import logging
from logging.handlers import RotatingFileHandler

# for google sheet functionality, maybe later
#import gspread
#from google.oauth2.service_account import Credentials

# TODO max message send is 2000, catch errors
# TODO gspread or similiar to automatically added data to google sheet
#       NOTE the above requires google app registration which doubles "paper work" 
# TODO should bot report back usings dms or in chat?
# TODO have an admin be able to add and remove allowed users

# NOTE
# - TOKEN is generated by discord for the bot, must be kept secret.
# - IDs are for my own discord server and channels for testing.
# - @commands.guild_only() means Don't allow this command in DMs, because the DM space has no ctx.
# - This bot assumes display_names are unique because 7cav requires it anyway

DEBUG = True

TZ = ZoneInfo("America/New_York")

# BOT CONFIG
load_dotenv()
TOKEN       = os.getenv('TOKEN')
GUILD_ID    = int(os.getenv('GUILD_ID')) # guild is a discord server

ALLOWED_USERS = list(map(int, os.getenv('ALLOWED_USERS').split(',')))

AUTO_BACKUP = 1 # in minutes

# BOT LOGGING
logging.basicConfig(
    level=logging.INFO,
    format='{asctime} {levelname:<8} {name} {message}',
    datefmt='%Y-%m-%d %H:%M:%S',
    style='{',
    handlers=[
        logging.StreamHandler(),
        RotatingFileHandler('tntbot.log', maxBytes=5*1024*1024, backupCount=3)
    ]
)

LOG = logging.getLogger('tntbot')

def ftimedelta(td: timedelta) -> str:
    # Formats a timedelta to a HH:MM:SS string.
    total_seconds = int(td.total_seconds())
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f'{hours:02}:{minutes:02}:{seconds:02}'

@dataclass
class MemberRecord:
    display_name: str
    last_joined: Optional[datetime] = field(default=None)
    duration: timedelta = field(default_factory=timedelta)

    def on_join(self):
        self.last_joined = datetime.now(TZ)

    def on_leave(self):
        if self.last_joined:
            self.duration += datetime.now(TZ) - self.last_joined
            self.last_joined = None

    # when we want an updated duration without stopping
    def snapshot(self):
        if self.last_joined is not None:
            self.on_leave()
            self.on_join()

@dataclass
class WatchJob:
    member_id: int # needed to dm members
    created_by: str
    name: str
    channel_ids: set[int]
    start: datetime
    end: datetime
    report_to: int # report outputs to this channel
    attendance: dict[int, dict[int, MemberRecord]] = field(default_factory=dict)
    status: str = "waiting"
    cav_only: bool = False
    interrupted: bool = False

    def __post_init__(self):
        for channel_id in self.channel_ids:
            self.attendance[channel_id] = {}

    def valid_member(self, member):
        # Ignore bots
        if member.bot:
            return None

        # Ignore non-cav and retired members
        if self.cav_only:
            # Example: 'ABC.Name.XYZ Cadre' matches
            match = re.match(r'^([0-9A-Z]{1,3})\.([0-9a-zA-Z,]+)\.([0-9A-Z]{1,3}) (.+)$', member.display_name)
            if not match:
                return None
            else:
                if 'RET' in match.group(4):
                    return None

        return member

    def record_join(self, channel_id: int, member: discord.Member):
        if not self.valid_member(member):
            return
        if member.id not in self.attendance[channel_id]:
            # If member is not being recorded, start new record
            record = MemberRecord(
                display_name=member.display_name,
                last_joined=datetime.now(TZ),
                duration=timedelta(),
            )
            self.attendance[channel_id][member.id] = record
        else:
            record = self.attendance[channel_id][member.id]
            # snapshot because members could join while already joined because the bot was disconnected.
            record.snapshot()

    def record_leave(self, channel_id: int, member: discord.Member):
        if not self.valid_member(member):
            return
        if member.id in self.attendance[channel_id]:
            self.attendance[channel_id][member.id].on_leave()

    def fstart(self):
        return self.start.strftime("%H:%M:%S")

    def fend(self):
        return self.end.strftime("%H:%M:%S")

class AttendanceCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.jobs: dict[str, tuple[WatchJob, asyncio.Task]] = {}
        self.watch_list: dict[int, list[WatchJob]] = defaultdict(list) 

        # For polling channels in real time and comparing the results from the previous poll
        self.poll_cache: dict[str, set[str]] = {}

        # Start auto backup
        self.auto_backup.start()

    @tasks.loop(minutes=AUTO_BACKUP)
    async def auto_backup(self):
        LOG.info(f"Automatically backing up task reports. (every {AUTO_BACKUP} minutes)")
        self.backup_reports()

    @auto_backup.before_loop
    async def before_auto_backup(self):
        await self.bot.wait_until_ready()

    @commands.command(enabled=DEBUG)
    async def debug_on_disconnect(self, ctx):
        await self.on_disconnect()

    @commands.Cog.listener()
    async def on_disconnect(self):
        self.backup_reports(interrupted = True)
        LOG.info("Bot was disconnected.")

    def backup_reports(self, interrupted: bool = False):
        # Back up each job report to a log file
        for name, (job, task) in self.jobs.items():
            job.interrupted = interrupted
            report = self.build_report(job)
            LOG.info(f"Report created for task: {name}.")
            try:
                with open(f"logs/{name}.log", "w") as f:
                    f.write(report)
                    LOG.info(f"Report written to {name}.log")
            except OSError as e:
                LOG.error(f"Failed to save report for job `{job.name}`: {e}")

    # direct message member
    async def dm(self, member_id: int, message: str):
        member = await self.bot.fetch_user(member_id)
        await member.send(message)

    @commands.command(enabled=DEBUG)
    async def debug_on_resumed(self, ctx):
        await self.on_resumed()

    @commands.Cog.listener()
    async def on_resumed(self): # Called when the bot has to reconnect
        # If reconnected we have to take attendance of all the channels being watched
        # to make sure it's up to date
        LOG.info(f"Bot resumed at {self.fnow()}, taking attendance to update...")

        now = datetime.now(TZ)

        for name, (job, task) in self.jobs.items():
            # If bot was disconnect the whole time of a task window just cancel it
            if now > job.end:
                job.status = "cancelled"
                task.cancel()
                LOG.info(f"Task `{job.name} was cancelled, because bot was disconnected at time.")

            if job.status != "watching":
                return

            LOG.info(f"Taking attendance on all watched channels.")

            for channel_id in job.channel_ids:
                channel = self.bot.get_channel(channel_id)
                if not channel:
                    continue

                # Who is in the channel
                in_channel: set[int] = set()

                # Update members who are still in channel
                for member in channel.members:
                    in_channel.add(member.id)
                    job.record_join(channel_id, member)

                # Update members aren't in channel anymore
                for member_id, record in job.attendance[channel_id].items():
                    if record.last_joined is not None:
                        if member_id not in in_channel:
                            LOG.debug(f"`{record.display_name}` left during outage, record that they left now.")
                            record.on_leave()

    def cog_unload(self):
        # if cog is unloaded while tasks are running, cancel them all
        for name, (job, task) in list(self.jobs.items()):
            task.cancel()

        # cancel auto backup
        self.auto_backup.cancel()

    def fnow(self):
        return datetime.now(TZ).strftime("%H:%M:%S")

    @commands.command()
    @commands.guild_only()
    async def poll(self, ctx: commands.Context, channel_name: str):
        channel = discord.utils.get(ctx.guild.channels, name=channel_name)

        if not channel:
            await ctx.send(f"ERROR: '{channel_name}' is not a valid channel.")
            return
        elif not isinstance(channel, discord.VoiceChannel):
            await ctx.send(f"ERROR: '{channel_name}' is not a voice channel.")
            return

        current: set[str] = {m.display_name for m in channel.members}
        lines = []

        lines.append(f"{len(current)} members in '{channel_name}' at {self.fnow()}")
        if current:
            lines.append("```")
            for name in current:
                lines.append(f"{name}")
            lines.append("```")

        if channel_name in self.poll_cache:
            previous = self.poll_cache[channel_name]

            # Operations allowed because of set type
            joined = current - previous
            left = previous - current

            # Members who joined the channel since the last poll
            if joined:
                lines.append("Joined since last poll")
                lines.append("```")
                for name in joined:
                    lines.append(f"{name}")
                lines.append("```")

            # Members who left the channel since the last poll
            if left:
                lines.append("Left since last poll")
                lines.append("```")
                for name in left:
                    lines.append(f"{name}")
                lines.append("```")

        # Update cache
        self.poll_cache[channel_name] = current

        await ctx.send("\n".join(lines))

    @commands.command()
    async def status(self, ctx: commands.Context):
        if not self.jobs:
            return await ctx.send("No watch tasks currently running.")

        now = datetime.now(TZ)
        lines = []

        # Check if jobs are running and if they are actually watching channels
        lines.append("Watch Status")
        lines.append("```")
        for name, (job, task) in self.jobs.items():
            line = f"'{job.name}' | {job.created_by} | {job.status} | {job.fstart()} | {job.fend()} |"
            for cid in job.channel_ids:
                channel = ctx.guild.get_channel(int(cid))
                line = line + (f" {channel.name}")
            lines.append(line)
        lines.append("```")

        await ctx.send("\n".join(lines))

    @commands.command()
    async def stop(self, ctx: commands.Context, name: str):
        if name not in self.jobs:
            return await ctx.send(f"No active task named `{name}` found.")

        _, task = self.jobs[name]
        task.cancel()
        await ctx.send(f"Task `{name}` has been stopped.")

    @commands.command()
    @commands.guild_only()
    async def watch_cav(self, ctx: commands.Context, name: str, start: str, duration: str, *channel_names: str):
        await self.watch(ctx, name, start, duration, *channel_names, cav_only = True)

    @commands.command()
    @commands.guild_only()
    async def watch(self, ctx: commands.Context, name: str, start: str, duration: str, *channel_names: str, cav_only = False):
        now = datetime.now(TZ)

        # Name validation
        if not re.match(r'^[A-Za-z0-9_]+$', name):
            return await ctx.send("ERROR: Task name can only contain letters, numbers, and underscores.")

        # Check if there are channels to watch
        if not channel_names:
            return await ctx.send("ERROR: You must provide at least one channel to watch.")

        # Check if job is already running
        if name in self.jobs:
            return await ctx.send(f"ERROR: task `{name}` already exists.")

        # Start time validation
        if start == "now": # lazy shortcut
            t_start = now
        else:
            try:
                t_start = datetime.strptime(start, "%H:%M")
            except (ValueError, TypeError) as e:
                return await ctx.send(f"ERROR: start time `{start}` must be in the form `hh:mm`.")

        # Duration validation
        pattern = re.compile(r'^(?:(\d+)h)?(?:(\d+)m)?$')

        try:
            match = pattern.match(duration)
            if not match or not any(match.groups()):
                raise ValueError
            d_hours = int(match.group(1) or 0)
            d_minutes = int(match.group(2) or 0)
        except ValueError as e:
            return await ctx.send(f"ERROR: duration `{duration}` must be in the form: `XhYm`, `Xh`, or `Ym` e.g. `25h30m`, `2h`, `30m`")

        # Convert from time to datetime for the current day
        dt_start = datetime.now(TZ).replace(hour=t_start.hour, minute=t_start.minute)
        # End time is start time + duration
        dt_end = dt_start + timedelta(hours=d_hours, minutes=d_minutes)

        # Check that the time ranges make sense
        if dt_start < now:
            return await ctx.send(f"ERROR: start time `{start}` can't be in the past.")

        # Find channel ids based on names and make sure channel exists and are a voice channels.
        channels = []
        for channel_name in channel_names:
            channel = discord.utils.get(ctx.guild.channels, name=channel_name)
            if not channel:
                return await ctx.send(f"ERROR: `{channel_name}` is not a valid channel.")
            elif not isinstance(channel, discord.VoiceChannel):
                return await ctx.send(f"ERROR: `{channel_name}` is not a voice channel.")
            channels.append(channel)

        # Create a new watch job
        job = WatchJob(
            member_id = ctx.author.id,
            created_by = ctx.author.display_name,
            name=name,
            channel_ids = {c.id for c in channels},
            start = dt_start,
            end = dt_end,
            report_to = ctx.channel.id,
            cav_only = cav_only,
        )

        # Create new bot task
        task = asyncio.create_task(self.job_start(job, channels), name=f"watchjob-{name}")

        # Assign the job it's task
        self.jobs[name] = (job, task)

        await ctx.send(
            f"Watch task `{job.name}` scheduled for {len(channels)} channel(s) "
            f"from `{job.fstart()}` to `{job.fend()}`."
        )

    async def job_start(self, job: WatchJob, channels: list[discord.VoiceChannel]) -> None:
        try:
            LOG.info(f"Task `{job.name}` started")

            # Wait until the start time
            now = datetime.now(TZ)
            remaining = (job.start - now).total_seconds()
            if job.start > now:
                LOG.info(f"Task `{job.name}` waiting for {remaining} seconds to start.")
                await asyncio.sleep(remaining)

            # Waiting is over start watching.
            job.status = "watching"

            # Add channels being watched by job to watch list
            for channel in channels:
                self.watch_list[channel.id].append(job)

            # Record members already in the channel
            for channel in channels:
                for member in channel.members:
                    job.record_join(channel.id, member)

            # Keep watching until the end time, then finish
            now = datetime.now(TZ)
            remaining = (job.end - now).total_seconds()
            if remaining > 0:
                LOG.info(f"Task `{job.name}` watching for {remaining} seconds, then stopping.")
                await asyncio.sleep(remaining)

        except asyncio.CancelledError:
            job.status = "cancelled" # cancelled
        finally:
            self.job_cleanup(job)
            await self.job_finished(job)

    def job_cleanup(self, job: WatchJob):
        LOG.info(f"Task `{job.name}` cleanup.")
        # Remove job
        self.jobs.pop(job.name, None)

        # Remove channels watched by jobs from watch list
        for channel_id in job.channel_ids:
            if channel_id in self.watch_list:
                self.watch_list[channel_id].remove(job)
                # If no more jobs are watching, remove channel from watch list
                if not self.watch_list[channel_id]:
                    del self.watch_list[channel_id]

    async def job_finished(self, job: WatchJob):
        if job.status == "cancelled":
            LOG.info(f"Task `{job.name}` cancelled.")
            return
        else:
            LOG.info(f"Task `{job.name}` finished.")

        report = self.build_report(job)
        channel = self.bot.get_channel(job.report_to)

        if channel:
            LOG.info(f"Sending final attendance for {job.name}.")
            return await self.bot.safe_send(channel, report)
        else:
            LOG.error(f"Could not find report channel `{job.report_to}`.")

    @commands.command()
    async def report(self, ctx: commands.Context, job_name: str):
        if job_name not in self.jobs:
            return await ctx.send(f"ERROR: Task `{job_name}` not found.")

        job, task = self.jobs[job_name]
        report = self.build_report(job)
        channel = self.bot.get_channel(job.report_to)

        if channel:
            return await channel.send(report)
        else:
            LOG.error(f"Could not find report channel `{job.report_to}`.")

    def build_report(self, job: WatchJob):
        now = datetime.now(TZ)

        # Get a snapshot of the attendance
        for members in job.attendance.values():
            for record in members.values():
                record.snapshot()

        # Merge member durations across all watched channels
        merged: dict[int, tuple[str, timedelta]] = {}
        for channel_id, members in job.attendance.items():
            for member_id, record in members.items():
                if member_id in merged:
                    name, total = merged[member_id]
                    merged[member_id] = (name, total + record.duration)
                else:
                    merged[member_id] = (record.display_name, record.duration)

        # Build output string
        lines = []

        if job.interrupted:
            lines.append("This task was interrupted and the results may not be accurate.")

        # Post to the report channel
        if now > job.end:
            lines.append(f"`{job.name}` final attendance")
        else:
            lines.append(f"`{job.name}` current attendance")

        # Added users in a nice format to be copied pasted.
        if merged:
            lines.append("```")
            for member_id, (display_name, total_duration) in merged.items():
                lines.append(f"{display_name};{ftimedelta(total_duration)}")
            lines.append("```")
        else:
            lines.append("No members recorded.")

        return "\n".join(lines)

    @commands.Cog.listener()
    async def on_voice_state_update(self, member: discord.Member, before: discord.VoiceState, after: discord.VoiceState):
        # If there are no channels to watch, don't do anything
        if not self.watch_list:
            return

        # Member left the channel, record their duration
        if before.channel and before.channel.id in self.watch_list:
            LOG.debug(f"{member.display_name} left channel.")
            for job in self.watch_list[before.channel.id]:
                job.record_leave(before.channel.id, member)

        # Member joined the join, record their last_joined
        if after.channel and after.channel.id in self.watch_list:
            LOG.debug(f"{member.display_name} joined channel.")
            for job in self.watch_list[after.channel.id]:
                job.record_join(after.channel.id, member)


class TNTBot(commands.Bot):
    def __init__(self):
        intents = discord.Intents.default()
        intents.members = True           # Required to see member lists
        intents.voice_states = True      # Required to see who is in voice channels
        intents.message_content = True   # Required to read command messages
        intents.messages = True          # Required to send messages
        intents.guilds = True            # Required to access guild/channel info
        super().__init__(command_prefix="!", intents=intents)

    async def setup_hook(self):
        LOG.info("AttendanceCog loaded.")
        await self.add_cog(AttendanceCog(self))

    async def on_ready(self):
        LOG.info(f"Logged in as {self.user}")

        for command in self.commands:
            LOG.info(f"Command {command.name} registered.")

        self.guild = self.get_guild(GUILD_ID)

        if self.guild is None:
            LOG.error(f"Could not find guild with ID {GUILD_ID}.")
            return

    async def on_message(self, message):
        if (message.author.id in ALLOWED_USERS):
            LOG.info(f"{message.author.display_name} sent message `{message.content}`")
            await self.process_commands(message)

    async def on_command_error(self, ctx, error):
        # Command does not exist
        if isinstance(error, commands.CommandNotFound):
            return await ctx.send(f"Unknown command. Use `{ctx.prefix}help` to see available commands.")

        # Command missing required argument
        elif isinstance(error, commands.MissingRequiredArgument):
            return await ctx.send(f"Error: Missing Required Arugment(s)")

        # Command is on cooldown
        elif isinstance(error, commands.CommandOnCooldown):
            if ctx.author.id is self.owner_id:
                ctx.command.reset_cooldown(ctx)
                return await ctx.command.reinvoke(ctx)
            cooldowns = {
                commands.BucketType.default: f'for the whole bot.',
                commands.BucketType.user:    f'for you.',
                commands.BucketType.guild:   f'for this server.',
                commands.BucketType.channel: f'for this channel.',
                commands.BucketType.member:  f'cooldown for you.',
                commands.BucketType.category:f'for this channel category.',
                commands.BucketType.role:    f'for your role.'
            }
            return await ctx.send(f'The command `{ctx.command}` is on cooldown {cooldowns[error.cooldown.type]} ')

        # Bot lacks permissions
        elif isinstance(error, commands.BotMissingPermissions):
            permissions = '\n'.join([f'> {permission}' for permission in error.missing_perms])
            message = f'Bot is missing the following permissions required to run the command `{ctx.command}`.\n{permissions}'
            try:
                return await ctx.send(message)
            except discord.Forbidden:
                try:
                    return await ctx.author.send(message)
                except discord.Forbidden:
                    return

        # Discord servers are having issues
        if isinstance(error.original, discord.HTTPException):
            LOG.error(f"HTTP {error.original.status} error in command: {error.original}")
            return await ctx.send(f"Discord error, please try again later.")

        raise error

    # If discord throws 503, 429 or 500 https errors, we can wait a bit and try again later
    async def safe_send(self, channel: discord.TextChannel, message: str, retries: int = 3, delay: int = 5):
        LOG.info("Using safe send.")
        for attempt in range(retries):
            try:
                return await channel.send(message)
            except discord.HTTPException as e:
                LOG.warning(f"HTTP {e.status} on attempt {attempt+1}/{retries}: {e}")
                if e.status not in {429, 500, 503} or attempt >= retries - 1:
                    LOG.error(f"Giving up on message after {attempt+1} attempts.")
                    return
                await asyncio.sleep(delay)

class HelpCommand(commands.MinimalHelpCommand):
    async def send_pages(self):
        destination = self.get_destination()
        for page in self.paginator.pages:
            emby = discord.Embed(description=page)
            await destination.send(embed=emby)

bot = TNTBot()
bot.help_command = HelpCommand()
bot.run(TOKEN, log_handler=None)
