import os
from datetime import datetime, timedelta
import discord
from zoneinfo import ZoneInfo
import asyncio
from discord.ext import tasks,commands
from dotenv import load_dotenv

# TNTBOT INFO
# - TOKEN is generated by discord for the bot, must be kept secret.
# - IDs are for my own discord server and channels for testing.
# - A guild is a discord server.

DEBUG = True

tz = ZoneInfo("America/New_York")

# BOT CONFIG
load_dotenv()
TOKEN       = os.getenv('TOKEN')
GUILD_ID    = int(os.getenv('GUILD_ID'))
EAST_ID     = int(os.getenv('EAST_ID'))
CENTRAL_ID  = int(os.getenv('CENTRAL_ID'))

ALLOWED_USERS = list(map(int, os.getenv('ALLOWED_USERS').split(',')))

TNT_START = datetime.now(tz).replace(hour=19, minute=0)
TNT_END   = datetime.now(tz).replace(hour=23, minute=0)
TNT_CHECK_COUNT = 10 
TNT_CHECK_MINUTES = int(((TNT_END - TNT_START) / TNT_CHECK_COUNT).total_seconds() / 60)

class AttendanceCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.check_attendance.start()

    def cog_unload(self):
        # Cancel taskes if cog is unloaded
        self.check_attendance.cancel()

    # TODO count = 1 for testing, replace later
    @tasks.loop(count = 1)
    async def check_attendance(self):
        # TODO keep a record of the users

        east = self.bot.get_channel(EAST_ID)
        central = self.bot.get_channel(CENTRAL_ID)

        if east:
            print("Members in 'east':")
            members = east.members
            for member in members:
                print(member.name)
        else:
            print("ERROR: Could not find channel 'east'")

        # TODO refactor
        if central:
            print("Members in 'central':")
            members = central.members
            for member in members:
                print(member.name)
        else:
            print("ERROR: Could not find channel 'east'")

    @check_attendance.after_loop
    async def after_check_attendance(self):
        self.bot.dispatch("attendance_taken")

    def guild_name(self):
        guild = self.bot.get_guild(GUILD_ID)
        return guild.name

    @check_attendance.before_loop
    async def before_check_attendance(self):
        print("Waiting until time")
        await self.bot.wait_until_ready()

    def guild_name(self):
        guild = self.bot.get_guild(GUILD_ID)
        return guild.name

    async def check_channel(self, channel):
        # Does channel exist?
        if channel is None:
            print(f"ERROR: Could not find channel with ID {TARGET_CHANNEL_ID}.")
            return
        if not isinstance(channel, discord.VoiceChannel):
            print(f"ERROR: Channel '{channel.name}' is not a voice channel.")
            return

        # Try to join channel
        print(f"Joining voice channel: '{channel.name}' in '{self.guild_name()}'")
        try:
            await channel.connect()
            print("Successfully joined the voice channel.")
        except discord.ClientException:
            print("Already connected to a voice channel in this guild.")

        # Get a list of the members in the channel
        # TODO create dictionary to count occurrences
        members = channel.members
        print(f"Members in '{channel.name}' ({len(members)} total):")
        if members:
            for member in members:
                print(f"{member.display_name}")
        else:
            print(f"{channel.name} is empty.")

        # Done. Leave the channel.
        print(f"Leaving voice channel: '{channel.name}' in '{self.guild_name()}'")
        try:
            await channel.guild.voice_client.disconnect()
            print("Successfully disconnected from voice channel.")
        except discord.ClientException:
            print("ERROR Could not disconnect.")

    @commands.command()
    @commands.guild_only() # Don't allow this command in DMs, because the DM space has no ctx.
    async def list_users(self, ctx, *, channel_name: str):
        channel_id = 0
        channel = discord.utils.get(ctx.guild.channels, name=channel_name)
        if channel:
            members = channel.members
            out = ""
            for member in members:
                out = out + member.display_name + "\n"
            await ctx.send(f"Members in Channel {channel.name} ({channel.id}) \n{out}")
        else:
            await ctx.send("ERROR Channel Not Found")

    @commands.command()
    @commands.guild_only() # Don't allow this command in DMs, because the DM space has no ctx.
    async def announce_tnt(self, ctx):
        start = int(TNT_START.timestamp()) 
        end = int(TNT_END.timestamp()) 
        message = f"""
Trenched n' Tuesday <t:{start}:R>. Let’s get to seeding. 

Official Run Time: <t:{start}:t> to <t:{end}:t> To Earn Operational Credit: Be in either Tactical Realism East or Central voice channels AND play on our servers for at least 1 hour total 

7th Cav Squad Limits: 
4 in infantry 
2 in tanks and artillery
1 in recon

Please do not :lock: squads (after all, this is a community/recruiting event)
"""
        await ctx.send(TNTMessage())

class TNTBot(commands.Bot):
    def __init__(self):
        guild = None
        intents = discord.Intents.default()
        intents.members = True           # Required to see member lists
        intents.voice_states = True      # Required to see who is in voice channels
        intents.message_content = True   # Required to read command messages
        intents.messages = True          # Required to send messages
        intents.guilds = True            # Required to access guild/channel info
        super().__init__(command_prefix="!", intents=intents)

    async def setup_hook(self):
        print("AttendanceCog loaded.")
        await self.add_cog(AttendanceCog(bot))

    async def on_attendance_taken(self):
        print ("Attendance taken.")
        #await self.close()

    async def on_ready(self):
        print(f"Logged in as {self.user}")
        print("Registered commands:")
        for command in self.commands:
            print(f"- {command.name}")
        self.guild = self.get_guild(GUILD_ID)
        if self.guild is None:
            print(f"Could not find guild with ID {GUILD_ID}. "
                  "ERROR: Make sure the bot has been invited to that server.")
            return

    async def on_message(self, message):
        if (message.author.id in ALLOWED_USERS):
            print(f"{message.content}")
            await self.process_commands(message)

    async def on_command_error(self, ctx, error):
        if isinstance(error, commands.CommandNotFound):
            await ctx.send(f"Unknown command. Use `{ctx.prefix}help` to see available commands.")
            return
        raise error

class HelpCommand(commands.MinimalHelpCommand):
    async def send_pages(self):
        destination = self.get_destination()
        for page in self.paginator.pages:
            emby = discord.Embed(description=page)
            await destination.send(embed=emby)

bot = TNTBot()
bot.help_command = HelpCommand()
bot.run(TOKEN)
